# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 62) do

  create_table "appels", :force => true do |t|
    t.column "beneficiaire_id", :integer
    t.column "ingenieur_id",    :integer
    t.column "debut",           :datetime
    t.column "fin",             :datetime
    t.column "contrat_id",      :integer,  :default => 0, :null => false
    t.column "demande_id",      :integer
  end

  add_index "appels", ["beneficiaire_id"], :name => "index_appels_on_beneficiaire_id"
  add_index "appels", ["ingenieur_id"], :name => "index_appels_on_ingenieur_id"
  add_index "appels", ["contrat_id"], :name => "index_appels_on_contrat_id"

  create_table "arches", :force => true do |t|
    t.column "nom", :string, :default => "", :null => false
  end

  create_table "authors", :force => true do |t|
    t.column "page_id", :integer
    t.column "name",    :string
  end

  create_table "beers", :force => true do |t|
    t.column "name",   :string
    t.column "rating", :integer
  end

  create_table "beers_drunkards", :id => false, :force => true do |t|
    t.column "beer_id",     :integer
    t.column "drunkard_id", :integer
  end

  create_table "beneficiaires", :force => true do |t|
    t.column "client_id",            :integer, :default => 0,    :null => false
    t.column "beneficiaire_id",      :integer
    t.column "identifiant_id",       :integer, :default => 0,    :null => false
    t.column "notifier_subalternes", :boolean, :default => true, :null => false
    t.column "notifier",             :boolean, :default => true, :null => false
    t.column "notifier_cc",          :boolean, :default => true, :null => false
  end

  add_index "beneficiaires", ["client_id"], :name => "beneficiaires_client_id_index"
  add_index "beneficiaires", ["beneficiaire_id"], :name => "beneficiaires_beneficiaire_id_index"
  add_index "beneficiaires", ["identifiant_id"], :name => "beneficiaires_identifiant_id_index"

  create_table "binaires", :force => true do |t|
    t.column "paquet_id",             :integer, :default => 0, :null => false
    t.column "arch_id",               :integer, :default => 0, :null => false
    t.column "nom",                   :string
    t.column "configuration",         :text
    t.column "archive",               :string
    t.column "socle_id",              :integer
    t.column "fichierbinaires_count", :integer
  end

  add_index "binaires", ["paquet_id"], :name => "paquets_binaires_paquet_id_index"
  add_index "binaires", ["arch_id"], :name => "paquets_binaires_arch_id_index"

  create_table "binaires_contributions", :id => false, :force => true do |t|
    t.column "binaire_id",      :integer
    t.column "contribution_id", :integer
  end

  add_index "binaires_contributions", ["binaire_id"], :name => "binaires_correctifs_binaire_id_index"
  add_index "binaires_contributions", ["contribution_id"], :name => "binaires_correctifs_correctif_id_index"

  create_table "binaires_demandes", :id => false, :force => true do |t|
    t.column "binaire_id", :integer
    t.column "demande_id", :integer
  end

  add_index "binaires_demandes", ["binaire_id"], :name => "binaires_demandes_binaire_id_index"
  add_index "binaires_demandes", ["demande_id"], :name => "binaires_demandes_demande_id_index"

  create_table "changelogs", :force => true do |t|
    t.column "paquet_id",         :integer,  :default => 0,  :null => false
    t.column "date_modification", :datetime,                 :null => false
    t.column "nom_modification",  :string,   :default => "", :null => false
    t.column "text_modification", :text,     :default => "", :null => false
  end

  add_index "changelogs", ["paquet_id"], :name => "changelogs_paquet_id_index"

  create_table "clients", :force => true do |t|
    t.column "nom",                 :string,  :default => "", :null => false
    t.column "description",         :text,    :default => "", :null => false
    t.column "mailingliste",        :string,  :default => "", :null => false
    t.column "adresse",             :text,    :default => "", :null => false
    t.column "image_id",            :integer
    t.column "support_id",          :integer
    t.column "code_acces",          :string,  :default => "", :null => false
    t.column "beneficiaires_count", :integer
    t.column "chrono",              :string
  end

  add_index "clients", ["support_id"], :name => "clients_support_id_index"
  add_index "clients", ["image_id"], :name => "index_clients_on_image_id"

  create_table "clients_socles", :id => false, :force => true do |t|
    t.column "client_id", :integer
    t.column "socle_id",  :integer
  end

  add_index "clients_socles", ["client_id"], :name => "clients_socles_client_id_index"
  add_index "clients_socles", ["socle_id"], :name => "clients_socles_socle_id_index"

  create_table "commentaires", :force => true do |t|
    t.column "demande_id",     :integer,  :default => 0,     :null => false
    t.column "identifiant_id", :integer,  :default => 0,     :null => false
    t.column "piecejointe_id", :integer
    t.column "corps",          :text
    t.column "created_on",     :datetime
    t.column "updated_on",     :datetime
    t.column "prive",          :boolean,  :default => false, :null => false
    t.column "severite_id",    :integer
    t.column "statut_id",      :integer
    t.column "ingenieur_id",   :integer
  end

  add_index "commentaires", ["demande_id"], :name => "commentaires_demande_id_index"
  add_index "commentaires", ["piecejointe_id"], :name => "commentaires_piecejointe_id_index"
  add_index "commentaires", ["identifiant_id"], :name => "commentaires_identifiant_id_index"
  add_index "commentaires", ["ingenieur_id"], :name => "index_commentaires_on_ingenieur_id"

  create_table "communautes", :force => true do |t|
    t.column "nom",         :string,   :default => "", :null => false
    t.column "description", :text,     :default => "", :null => false
    t.column "url",         :string,   :default => "", :null => false
    t.column "created_on",  :datetime,                 :null => false
    t.column "updated_on",  :datetime,                 :null => false
  end

  create_table "competences", :force => true do |t|
    t.column "nom", :string, :default => "", :null => false
  end

  create_table "competences_ingenieurs", :id => false, :force => true do |t|
    t.column "ingenieur_id",  :integer, :default => 0, :null => false
    t.column "competence_id", :integer, :default => 0, :null => false
    t.column "niveau",        :integer
  end

  add_index "competences_ingenieurs", ["ingenieur_id"], :name => "competences_ingenieurs_ingenieur_id_index"
  add_index "competences_ingenieurs", ["competence_id"], :name => "competences_ingenieurs_competence_id_index"

  create_table "competences_logiciels", :id => false, :force => true do |t|
    t.column "competence_id", :integer, :default => 0, :null => false
    t.column "logiciel_id",   :integer, :default => 0, :null => false
  end

  add_index "competences_logiciels", ["logiciel_id"], :name => "competences_logiciels_logiciel_id_index"
  add_index "competences_logiciels", ["competence_id"], :name => "competences_logiciels_competence_id_index"

  create_table "conteneurs", :force => true do |t|
    t.column "nom", :string, :default => "", :null => false
  end

  create_table "contrats", :force => true do |t|
    t.column "client_id",     :integer,  :default => 0,     :null => false
    t.column "ouverture",     :datetime,                    :null => false
    t.column "cloture",       :datetime,                    :null => false
    t.column "paquets_count", :integer
    t.column "astreinte",     :boolean,  :default => false, :null => false
    t.column "socle",         :boolean,  :default => false, :null => false
    t.column "nom",           :string
    t.column "support",       :boolean,  :default => false
  end

  add_index "contrats", ["client_id"], :name => "contrats_client_id_index"

  create_table "contrats_engagements", :id => false, :force => true do |t|
    t.column "contrat_id",    :integer, :default => 0, :null => false
    t.column "engagement_id", :integer, :default => 0, :null => false
  end

  add_index "contrats_engagements", ["contrat_id"], :name => "contrats_engagements_contrat_id_index"
  add_index "contrats_engagements", ["engagement_id"], :name => "contrats_engagements_engagement_id_index"

  create_table "contrats_ingenieurs", :id => false, :force => true do |t|
    t.column "contrat_id",   :integer, :default => 0, :null => false
    t.column "ingenieur_id", :integer, :default => 0, :null => false
  end

  add_index "contrats_ingenieurs", ["ingenieur_id"], :name => "contrats_ingenieurs_ingenieur_id_index"
  add_index "contrats_ingenieurs", ["contrat_id"], :name => "contrats_ingenieurs_contrat_id_index"

  create_table "contributions", :force => true do |t|
    t.column "nom",                       :string,   :default => "", :null => false
    t.column "description",               :text,     :default => "", :null => false
    t.column "patch",                     :string,   :default => "", :null => false
    t.column "created_on",                :datetime,                 :null => false
    t.column "updated_on",                :datetime,                 :null => false
    t.column "id_mantis",                 :integer
    t.column "reverse_le",                :datetime
    t.column "description_fonctionnelle", :text,     :default => "", :null => false
    t.column "etatreversement_id",        :integer,  :default => 0,  :null => false
    t.column "cloture_le",                :datetime
    t.column "logiciel_id",               :integer,  :default => 0,  :null => false
    t.column "ingenieur_id",              :integer,  :default => 0,  :null => false
    t.column "typecontribution_id",       :integer,  :default => 0,  :null => false
    t.column "version",                   :string
    t.column "synthese",                  :text
  end

  add_index "contributions", ["logiciel_id"], :name => "index_contributions_on_logiciel_id"
  add_index "contributions", ["ingenieur_id"], :name => "index_contributions_on_ingenieur_id"

  create_table "contributions_paquets", :id => false, :force => true do |t|
    t.column "contribution_id", :integer
    t.column "paquet_id",       :integer, :default => 0, :null => false
  end

  add_index "contributions_paquets", ["paquet_id"], :name => "correctifs_paquets_paquet_id_index"
  add_index "contributions_paquets", ["contribution_id"], :name => "correctifs_paquets_correctif_id_index"

  create_table "correctifs_demandes", :id => false, :force => true do |t|
    t.column "correctif_id", :integer, :null => false
    t.column "demande_id",   :integer, :null => false
  end

  add_index "correctifs_demandes", ["correctif_id"], :name => "index_correctifs_demandes_on_correctif_id"
  add_index "correctifs_demandes", ["demande_id"], :name => "index_correctifs_demandes_on_demande_id"

  create_table "demande_versions", :force => true do |t|
    t.column "demande_id",      :integer
    t.column "version",         :integer
    t.column "beneficiaire_id", :integer,  :default => 0
    t.column "ingenieur_id",    :integer
    t.column "resume",          :string,   :default => ""
    t.column "description",     :text
    t.column "statut_id",       :integer,  :default => 0
    t.column "severite_id",     :integer,  :default => 0
    t.column "socle_id",        :integer
    t.column "logiciel_id",     :integer,  :default => 0
    t.column "reproductible",   :boolean,  :default => false
    t.column "created_on",      :datetime
    t.column "updated_on",      :datetime
    t.column "typedemande_id",  :integer,  :default => 0
    t.column "contribution_id", :integer
    t.column "mail_cc",         :string
  end

  create_table "demandes", :force => true do |t|
    t.column "beneficiaire_id",  :integer,  :default => 0,  :null => false
    t.column "ingenieur_id",     :integer
    t.column "resume",           :string,   :default => "", :null => false
    t.column "statut_id",        :integer,  :default => 0,  :null => false
    t.column "severite_id",      :integer,  :default => 0,  :null => false
    t.column "logiciel_id",      :integer,  :default => 0
    t.column "created_on",       :datetime
    t.column "updated_on",       :datetime
    t.column "typedemande_id",   :integer,  :default => 0,  :null => false
    t.column "contribution_id",  :integer
    t.column "socle_id",         :integer,  :default => 0,  :null => false
    t.column "mail_cc",          :string
    t.column "first_comment_id", :integer
    t.column "description",      :text
    t.column "contrat_id",       :integer,                  :null => false
  end

  add_index "demandes", ["contribution_id"], :name => "demandes_correctif_id_index"
  add_index "demandes", ["beneficiaire_id"], :name => "demandes_beneficiaire_id_index"
  add_index "demandes", ["ingenieur_id"], :name => "demandes_ingenieur_id_index"
  add_index "demandes", ["severite_id"], :name => "demandes_severite_id_index"
  add_index "demandes", ["typedemande_id"], :name => "demandes_typedemande_id_index"
  add_index "demandes", ["contrat_id"], :name => "index_demandes_on_contrat_id"

  create_table "demandes_paquets", :id => false, :force => true do |t|
    t.column "paquet_id",  :integer
    t.column "demande_id", :integer, :default => 0, :null => false
  end

  add_index "demandes_paquets", ["paquet_id"], :name => "demandes_paquets_paquet_id_index"
  add_index "demandes_paquets", ["demande_id"], :name => "demandes_paquets_demande_id_index"

  create_table "dependances", :force => true do |t|
    t.column "paquet_id", :integer,               :default => 0,  :null => false
    t.column "nom",       :string,                :default => "", :null => false
    t.column "sens",      :string,  :limit => 15, :default => "", :null => false
    t.column "version",   :string,                :default => "", :null => false
  end

  create_table "distributeurs", :force => true do |t|
    t.column "nom", :string, :default => "", :null => false
  end

  create_table "document_versions", :force => true do |t|
    t.column "document_id",     :integer
    t.column "version",         :integer
    t.column "identifiant_id",  :integer,  :default => 0
    t.column "typedocument_id", :integer,  :default => 0
    t.column "client_id",       :integer,  :default => 0
    t.column "titre",           :string,   :default => ""
    t.column "fichier",         :string,   :default => ""
    t.column "description",     :text
    t.column "created_on",      :datetime
    t.column "updated_on",      :datetime
    t.column "date_delivery",   :datetime
  end

  create_table "documents", :force => true do |t|
    t.column "identifiant_id",  :integer,  :default => 0,  :null => false
    t.column "typedocument_id", :integer,  :default => 0,  :null => false
    t.column "client_id",       :integer,  :default => 0,  :null => false
    t.column "titre",           :string,   :default => "", :null => false
    t.column "fichier",         :string,   :default => "", :null => false
    t.column "description",     :text,     :default => "", :null => false
    t.column "created_on",      :datetime,                 :null => false
    t.column "updated_on",      :datetime,                 :null => false
    t.column "version",         :integer
    t.column "date_delivery",   :datetime
  end

  add_index "documents", ["identifiant_id"], :name => "documents_identifiant_id_index"
  add_index "documents", ["typedocument_id"], :name => "documents_typedocument_id_index"
  add_index "documents", ["client_id"], :name => "documents_client_id_index"

  create_table "drunkards", :force => true do |t|
    t.column "name", :string
  end

  create_table "engagements", :force => true do |t|
    t.column "severite_id",    :integer, :default => 0,   :null => false
    t.column "contournement",  :float,   :default => 0.0
    t.column "correction",     :float,   :default => 0.0
    t.column "typedemande_id", :integer, :default => 0,   :null => false
  end

  add_index "engagements", ["severite_id", "typedemande_id"], :name => "engagements_severite_id_index"

  create_table "etapes", :force => true do |t|
    t.column "nom",         :string, :default => "", :null => false
    t.column "description", :text
  end

  create_table "etatreversements", :force => true do |t|
    t.column "nom",         :string, :default => "", :null => false
    t.column "description", :text,   :default => "", :null => false
  end

  create_table "fichierbinaires", :force => true do |t|
    t.column "binaire_id", :integer
    t.column "chemin",     :string
    t.column "taille",     :integer
  end

  add_index "fichierbinaires", ["binaire_id"], :name => "fichiers_binaires_paquet_binaire_id_index"

  create_table "fichiers", :force => true do |t|
    t.column "paquet_id", :integer, :default => 0,  :null => false
    t.column "chemin",    :string,  :default => ""
    t.column "taille",    :integer, :default => 0,  :null => false
  end

  add_index "fichiers", ["paquet_id"], :name => "fichiers_paquet_id"

  create_table "fournisseurs", :force => true do |t|
    t.column "nom", :string, :default => "", :null => false
  end

  create_table "glasses", :force => true do |t|
    t.column "name", :string
  end

  create_table "groupes", :force => true do |t|
    t.column "nom", :string, :limit => 80
  end

  create_table "identifiants", :force => true do |t|
    t.column "login",        :string,  :limit => 80
    t.column "password",     :string,  :limit => 40
    t.column "titre",        :string,                :default => "",    :null => false
    t.column "nom",          :string,                :default => "",    :null => false
    t.column "email",        :string,                :default => "",    :null => false
    t.column "telephone",    :string,                :default => "",    :null => false
    t.column "image_id",     :integer
    t.column "informations", :text,                  :default => "",    :null => false
    t.column "client",       :boolean,               :default => false, :null => false
    t.column "inactive",     :boolean,               :default => false
  end

  add_index "identifiants", ["image_id"], :name => "index_identifiants_on_image_id"

  create_table "identifiants_roles", :id => false, :force => true do |t|
    t.column "identifiant_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "role_id",        :integer, :limit => 10, :default => 0, :null => false
  end

  add_index "identifiants_roles", ["role_id"], :name => "roles_identifiants_FKIndex1"
  add_index "identifiants_roles", ["identifiant_id"], :name => "roles_identifiants_FKIndex2"

  create_table "images", :force => true do |t|
    t.column "image",       :string
    t.column "description", :string
  end

  create_table "ingenieurs", :force => true do |t|
    t.column "identifiant_id", :integer, :default => 0,     :null => false
    t.column "chef_de_projet", :boolean, :default => false, :null => false
    t.column "expert_ossa",    :boolean, :default => false, :null => false
    t.column "image_id",       :integer
  end

  add_index "ingenieurs", ["identifiant_id"], :name => "ingenieurs_identifiant_id_index"

  create_table "jourferies", :force => true do |t|
    t.column "jour", :datetime, :null => false
  end

  create_table "licenses", :force => true do |t|
    t.column "nom",          :string,  :limit => 63, :default => "", :null => false
    t.column "url",          :string,                :default => "", :null => false
    t.column "certifie_osi", :boolean
  end

  create_table "locked_pages", :force => true do |t|
    t.column "lock_version", :integer
    t.column "title",        :string
    t.column "type",         :string
  end

  create_table "locked_pages_revisions", :force => true do |t|
    t.column "page_id",      :integer
    t.column "version",      :integer
    t.column "title",        :string
    t.column "version_type", :string
    t.column "updated_at",   :datetime
  end

  create_table "logiciels", :force => true do |t|
    t.column "nom",         :string,  :default => "", :null => false
    t.column "referent",    :string
    t.column "resume",      :string,  :default => "", :null => false
    t.column "description", :text
    t.column "license_id",  :integer, :default => 0,  :null => false
    t.column "groupe_id",   :integer
    t.column "image_id",    :integer
  end

  add_index "logiciels", ["referent"], :name => "logiciels_referent"
  add_index "logiciels", ["license_id"], :name => "logiciels_license_id"
  add_index "logiciels", ["image_id"], :name => "index_logiciels_on_image_id"

  create_table "machines", :force => true do |t|
    t.column "socle_id",    :integer, :default => 0, :null => false
    t.column "acces",       :string
    t.column "virtuelle",   :boolean
    t.column "hote_id",     :integer
    t.column "description", :text
  end

  create_table "mainteneurs", :force => true do |t|
    t.column "nom", :string, :default => "", :null => false
  end

  create_table "news", :force => true do |t|
    t.column "subject",      :string,   :default => "", :null => false
    t.column "source",       :string,   :default => "", :null => false
    t.column "body",         :text
    t.column "created_on",   :datetime
    t.column "updated_on",   :datetime
    t.column "ingenieur_id", :integer,  :default => 0,  :null => false
    t.column "client_id",    :integer
    t.column "logiciel_id",  :integer,  :default => 0,  :null => false
  end

  add_index "news", ["ingenieur_id"], :name => "index_news_on_ingenieur_id"
  add_index "news", ["logiciel_id"], :name => "index_news_on_logiciel_id"
  add_index "news", ["subject"], :name => "index_news_on_subject"

  create_table "old_bouquets", :force => true do |t|
    t.column "nom", :string, :default => "", :null => false
  end

  create_table "old_classifications", :force => true do |t|
    t.column "logiciel_id", :integer, :default => 0, :null => false
    t.column "groupe_id",   :integer, :default => 0, :null => false
    t.column "bouquet_id",  :integer, :default => 0, :null => false
    t.column "client_id",   :integer, :default => 0, :null => false
  end

  create_table "page_versions", :force => true do |t|
    t.column "page_id",    :integer
    t.column "version",    :integer
    t.column "title",      :string
    t.column "body",       :text
    t.column "updated_on", :datetime
    t.column "author_id",  :integer
    t.column "revisor_id", :integer
  end

  create_table "pages", :force => true do |t|
    t.column "version",    :integer
    t.column "title",      :string
    t.column "body",       :text
    t.column "updated_on", :datetime
    t.column "author_id",  :integer
    t.column "revisor_id", :integer
  end

  create_table "paquets", :force => true do |t|
    t.column "logiciel_id",      :integer,               :default => 0,    :null => false
    t.column "nom",              :string,  :limit => 60, :default => "",   :null => false
    t.column "version",          :string,  :limit => 60, :default => "",   :null => false
    t.column "release",          :string,  :limit => 60, :default => "",   :null => false
    t.column "conteneur_id",     :integer,               :default => 0,    :null => false
    t.column "paquet_id",        :integer,               :default => 0,    :null => false
    t.column "distributeur_id",  :integer,               :default => 0,    :null => false
    t.column "mainteneur_id",    :integer,               :default => 0,    :null => false
    t.column "contrat_id",       :integer,               :default => 0,    :null => false
    t.column "taille",           :integer,               :default => 0,    :null => false
    t.column "fournisseur_id",   :integer,               :default => 0,    :null => false
    t.column "configuration",    :text,                  :default => "",   :null => false
    t.column "fichiers_count",   :integer
    t.column "changelogs_count", :integer
    t.column "active",           :boolean,               :default => true
  end

  add_index "paquets", ["nom", "version", "release"], :name => "paquets_nvr"
  add_index "paquets", ["paquet_id"], :name => "paquets_paquet_id"
  add_index "paquets", ["logiciel_id"], :name => "paquets_logiciel_id_index"
  add_index "paquets", ["conteneur_id"], :name => "paquets_conteneur_id_index"
  add_index "paquets", ["paquet_id"], :name => "paquets_paquet_id_index"
  add_index "paquets", ["distributeur_id"], :name => "paquets_distributeur_id_index"
  add_index "paquets", ["mainteneur_id"], :name => "paquets_mainteneur_id_index"
  add_index "paquets", ["contrat_id"], :name => "paquets_contrat_id_index"
  add_index "paquets", ["fournisseur_id"], :name => "paquets_fournisseur_id_index"

  create_table "permissions", :force => true do |t|
    t.column "name", :string,               :default => "", :null => false
    t.column "info", :string, :limit => 80
  end

  create_table "permissions_roles", :id => false, :force => true do |t|
    t.column "role_id",       :integer, :limit => 10, :default => 0, :null => false
    t.column "permission_id", :integer, :limit => 10, :default => 0, :null => false
  end

  add_index "permissions_roles", ["permission_id"], :name => "permissions_roles_FKIndex1"
  add_index "permissions_roles", ["role_id"], :name => "permissions_roles_FKIndex2"

  create_table "piecejointes", :force => true do |t|
    t.column "file", :string, :default => "", :null => false
  end

  create_table "preferences", :force => true do |t|
    t.column "identifiant_id", :integer,                    :null => false
    t.column "mail_text",      :boolean, :default => false
    t.column "all_mail",       :boolean, :default => true
    t.column "digest_daily",   :boolean, :default => false
    t.column "digest_weekly",  :boolean, :default => false
  end

  add_index "preferences", ["identifiant_id"], :name => "index_preferences_on_identifiant_id"

  create_table "roles", :force => true do |t|
    t.column "nom",  :string, :limit => 40
    t.column "info", :string, :limit => 80
  end

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "session_id_idx"

  create_table "severites", :force => true do |t|
    t.column "nom", :string
  end

  create_table "socles", :force => true do |t|
    t.column "nom",            :string,  :default => "", :null => false
    t.column "binaires_count", :integer
  end

  create_table "statuts", :force => true do |t|
    t.column "nom",         :string, :default => "", :null => false
    t.column "description", :text,   :default => "", :null => false
  end

  create_table "supports", :force => true do |t|
    t.column "nom",                  :string,  :default => "",    :null => false
    t.column "maintenance",          :boolean, :default => false
    t.column "assistance_tel",       :boolean, :default => false
    t.column "veille_technologique", :boolean, :default => false
    t.column "ouverture",            :integer, :default => 0,     :null => false
    t.column "fermeture",            :integer, :default => 0,     :null => false
    t.column "newsletter",           :boolean
    t.column "duree_intervention",   :integer
  end

  create_table "temp", :id => false, :force => true do |t|
    t.column "contrat_id", :integer,                                :null => false
    t.column "nom",        :string,  :limit => 105, :default => "", :null => false
    t.column "version",    :string,  :limit => 55,  :default => "", :null => false
    t.column "release",    :string,  :limit => 55,  :default => "", :null => false
    t.column "chemin",     :string,                 :default => "", :null => false
    t.column "taille",     :string,                 :default => "", :null => false
    t.column "paquet_id",  :integer
  end

  add_index "temp", ["nom", "version", "release"], :name => "temp_nvr"
  add_index "temp", ["paquet_id"], :name => "temp_pid"

  create_table "typecontributions", :force => true do |t|
    t.column "nom",         :string, :default => "", :null => false
    t.column "description", :text,   :default => "", :null => false
  end

  create_table "typedemandes", :force => true do |t|
    t.column "nom", :string, :default => "", :null => false
  end

  create_table "typedocuments", :force => true do |t|
    t.column "nom",         :string, :default => "", :null => false
    t.column "description", :text,   :default => "", :null => false
  end

  create_table "typeurls", :force => true do |t|
    t.column "nom", :string, :default => "", :null => false
  end

  create_table "urllogiciels", :force => true do |t|
    t.column "logiciel_id", :integer, :default => 0,  :null => false
    t.column "typeurl_id",  :integer, :default => 0,  :null => false
    t.column "valeur",      :string,  :default => "", :null => false
  end

  add_index "urllogiciels", ["logiciel_id"], :name => "urllogiciels_logiciel_id_index"
  add_index "urllogiciels", ["typeurl_id"], :name => "urllogiciels_typeurl_id_index"

  create_table "urlreversements", :force => true do |t|
    t.column "contribution_id", :integer
    t.column "valeur",          :string,  :default => "", :null => false
  end

end
